package com.cantor.ipplan.db;

// Generated 12.04.2013 19:58:46 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Calendar generated by hbm2java
 */
@Entity
@Table(name = "CALENDAR")
public class Calendar implements java.io.Serializable {

	private int bargainId;
	private Bargain bargain;
	private String calendarGoogleId;

	public Calendar() {
	}

	public Calendar(Bargain bargain) {
		this.bargain = bargain;
	}

	public Calendar(Bargain bargain, String calendarGoogleId) {
		this.bargain = bargain;
		this.calendarGoogleId = calendarGoogleId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BARGAIN_ID", unique = true, nullable = false)
	public int getBargainId() {
		return this.bargainId;
	}

	public void setBargainId(int bargainId) {
		this.bargainId = bargainId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Bargain getBargain() {
		return this.bargain;
	}

	public void setBargain(Bargain bargain) {
		this.bargain = bargain;
	}

	@Column(name = "CALENDAR_GOOGLE_ID", length = 256)
	public String getCalendarGoogleId() {
		return this.calendarGoogleId;
	}

	public void setCalendarGoogleId(String calendarGoogleId) {
		this.calendarGoogleId = calendarGoogleId;
	}

}
