package com.cantor.ipplan.db;

// Generated 12.04.2013 19:58:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Contract generated by hbm2java
 */
@Entity
@Table(name = "CONTRACT")
public class Contract implements java.io.Serializable {

	private int contractId;
	private Customer customer;
	private String contractName;
	private byte[] contractData;
	private String contractUri;
	private Set<Bargain> bargains = new HashSet<Bargain>(0);

	public Contract() {
	}

	public Contract(int contractId, Customer customer, String contractName) {
		this.contractId = contractId;
		this.customer = customer;
		this.contractName = contractName;
	}

	public Contract(int contractId, Customer customer, String contractName,
			byte[] contractData, String contractUri, Set<Bargain> bargains) {
		this.contractId = contractId;
		this.customer = customer;
		this.contractName = contractName;
		this.contractData = contractData;
		this.contractUri = contractUri;
		this.bargains = bargains;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "NEWRECORDID")
	@Column(name = "CONTRACT_ID", unique = true, nullable = false)
	public int getContractId() {
		return this.contractId;
	}

	public void setContractId(int contractId) {
		this.contractId = contractId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ID", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "CONTRACT_NAME", nullable = false, length = 256)
	public String getContractName() {
		return this.contractName;
	}

	public void setContractName(String contractName) {
		this.contractName = contractName;
	}

	@Column(name = "CONTRACT_DATA")
	public byte[] getContractData() {
		return this.contractData;
	}

	public void setContractData(byte[] contractData) {
		this.contractData = contractData;
	}

	@Column(name = "CONTRACT_URI", length = 2048)
	public String getContractUri() {
		return this.contractUri;
	}

	public void setContractUri(String contractUri) {
		this.contractUri = contractUri;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contract")
	public Set<Bargain> getBargains() {
		return this.bargains;
	}

	public void setBargains(Set<Bargain> bargains) {
		this.bargains = bargains;
	}

}
