package com.cantor.ipplan.db;

// Generated 12.04.2013 19:58:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "CUSTOMER")
public class Customer implements java.io.Serializable {

	private int customerId;
	private String customerName;
	private String customerLookupKey;
	private Set<Contract> contracts = new HashSet<Contract>(0);
	private Set<Bargain> bargains = new HashSet<Bargain>(0);

	public Customer() {
	}

	public Customer(int customerId, String customerName) {
		this.customerId = customerId;
		this.customerName = customerName;
	}

	public Customer(int customerId, String customerName,
			String customerLookupKey, Set<Contract> contracts,
			Set<Bargain> bargains) {
		this.customerId = customerId;
		this.customerName = customerName;
		this.customerLookupKey = customerLookupKey;
		this.contracts = contracts;
		this.bargains = bargains;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "NEWRECORDID")
	@Column(name = "CUSTOMER_ID", unique = true, nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Column(name = "CUSTOMER_NAME", nullable = false, length = 256)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "CUSTOMER_LOOKUP_KEY", length = 256)
	public String getCustomerLookupKey() {
		return this.customerLookupKey;
	}

	public void setCustomerLookupKey(String customerLookupKey) {
		this.customerLookupKey = customerLookupKey;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Contract> getContracts() {
		return this.contracts;
	}

	public void setContracts(Set<Contract> contracts) {
		this.contracts = contracts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Bargain> getBargains() {
		return this.bargains;
	}

	public void setBargains(Set<Bargain> bargains) {
		this.bargains = bargains;
	}

}
