package com.cantor.ipplan.db;

// Generated 12.04.2013 19:58:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Puser generated by hbm2java
 */
@Entity
@Table(name = "PUSER")
public class Puser implements java.io.Serializable {

	private int puserId;
	private Puser puser;
	private String puserLogin;
	private Set<Bargain> bargains = new HashSet<Bargain>(0);
	private Set<Status> statuses = new HashSet<Status>(0);
	private Set<Puser> pusers = new HashSet<Puser>(0);

	public Puser() {
	}

	public Puser(int puserId, String puserLogin) {
		this.puserId = puserId;
		this.puserLogin = puserLogin;
	}

	public Puser(int puserId, Puser puser, String puserLogin,
			Set<Bargain> bargains, Set<Status> statuses, Set<Puser> pusers) {
		this.puserId = puserId;
		this.puser = puser;
		this.puserLogin = puserLogin;
		this.bargains = bargains;
		this.statuses = statuses;
		this.pusers = pusers;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "NEWRECORDID")
	@Column(name = "PUSER_ID", unique = true, nullable = false)
	public int getPuserId() {
		return this.puserId;
	}

	public void setPuserId(int puserId) {
		this.puserId = puserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OWNER_PUSER_ID")
	public Puser getPuser() {
		return this.puser;
	}

	public void setPuser(Puser puser) {
		this.puser = puser;
	}

	@Column(name = "PUSER_LOGIN", nullable = false, length = 320)
	public String getPuserLogin() {
		return this.puserLogin;
	}

	public void setPuserLogin(String puserLogin) {
		this.puserLogin = puserLogin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puser")
	public Set<Bargain> getBargains() {
		return this.bargains;
	}

	public void setBargains(Set<Bargain> bargains) {
		this.bargains = bargains;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puser")
	public Set<Status> getStatuses() {
		return this.statuses;
	}

	public void setStatuses(Set<Status> statuses) {
		this.statuses = statuses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puser")
	public Set<Puser> getPusers() {
		return this.pusers;
	}

	public void setPusers(Set<Puser> pusers) {
		this.pusers = pusers;
	}

}
