package com.cantor.ipplan.db.ud;

// Generated 12.04.2013 19:58:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Agreed generated by hbm2java
 */
@Entity
@Table(name = "AGREED")
public class Agreed implements java.io.Serializable {

	private int agreedId;
	private Bargain bargain;
	private Date agreedDate;
	private String agreedNote;

	public Agreed() {
	}

	public Agreed(int agreedId, Bargain bargain, Date agreedDate) {
		this.agreedId = agreedId;
		this.bargain = bargain;
		this.agreedDate = agreedDate;
	}

	public Agreed(int agreedId, Bargain bargain, Date agreedDate,
			String agreedNote) {
		this.agreedId = agreedId;
		this.bargain = bargain;
		this.agreedDate = agreedDate;
		this.agreedNote = agreedNote;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "NEWRECORDID")
	@Column(name = "AGREED_ID", unique = true, nullable = false)
	public int getAgreedId() {
		return this.agreedId;
	}

	public void setAgreedId(int agreedId) {
		this.agreedId = agreedId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BARGAIN_ID", nullable = false)
	public Bargain getBargain() {
		return this.bargain;
	}

	public void setBargain(Bargain bargain) {
		this.bargain = bargain;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "AGREED_DATE", nullable = false, length = 10)
	public Date getAgreedDate() {
		return this.agreedDate;
	}

	public void setAgreedDate(Date agreedDate) {
		this.agreedDate = agreedDate;
	}

	@Column(name = "AGREED_NOTE", length = 200)
	public String getAgreedNote() {
		return this.agreedNote;
	}

	public void setAgreedNote(String agreedNote) {
		this.agreedNote = agreedNote;
	}

}
