package com.cantor.ipplan.db.ud;

// Generated 12.04.2013 19:58:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.cantor.ipplan.db.up.PUser;

/**
 * Bargain generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "BARGAIN", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ROOT_BARGAIN_ID", "BARGAIN_VER" }))
public class Bargain implements java.io.Serializable {

	private int bargainId;
	private String bargainName;
	private Contract contract;
	private Customer customer;
	private PUser puser;
	private Bargain bargain;
	private Status status;
	private int bargainVer;
	private Date bargainStart;
	private Date bargainFinish;
	private Integer bargainRevenue;
	private Integer bargainPrepayment;
	private Integer bargainCosts;
	private Integer bargainPaymentCosts;
	private Integer bargainFine;
	private Integer bargainTax;
	private Calendar calendar;
	private Set<Bargaincosts> bargaincostses = new HashSet<Bargaincosts>(0);
	private Set<Bargain> bargains = new HashSet<Bargain>(0);
	private Set<Agreed> agreeds = new HashSet<Agreed>(0);

	public Bargain() {
	}

	public Bargain(int bargainId, Customer customer, PUser puser,
			Bargain bargain, int bargainVer, Date bargainStart,
			Date bargainFinish) {
		this.bargainId = bargainId;
		this.customer = customer;
		this.puser = puser;
		this.bargain = bargain;
		this.bargainVer = bargainVer;
		this.bargainStart = bargainStart;
		this.bargainFinish = bargainFinish;
	}

	public Bargain(int bargainId, Contract contract, Customer customer,
			PUser puser, Bargain bargain, Status status, int bargainVer,
			Date bargainStart, Date bargainFinish, Integer bargainRevenue,
			Integer bargainPrepayment, Integer bargainCosts,
			Integer bargainPaymentCosts, Integer bargainFine,
			Integer bargainTax, Calendar calendar,
			Set<Bargaincosts> bargaincostses, Set<Bargain> bargains,
			Set<Agreed> agreeds) {
		this.bargainId = bargainId;
		this.contract = contract;
		this.customer = customer;
		this.puser = puser;
		this.bargain = bargain;
		this.status = status;
		this.bargainVer = bargainVer;
		this.bargainStart = bargainStart;
		this.bargainFinish = bargainFinish;
		this.bargainRevenue = bargainRevenue;
		this.bargainPrepayment = bargainPrepayment;
		this.bargainCosts = bargainCosts;
		this.bargainPaymentCosts = bargainPaymentCosts;
		this.bargainFine = bargainFine;
		this.bargainTax = bargainTax;
		this.calendar = calendar;
		this.bargaincostses = bargaincostses;
		this.bargains = bargains;
		this.agreeds = agreeds;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "NEWRECORDID")
	@Column(name = "BARGAIN_ID", unique = true, nullable = false)
	public int getBargainId() {
		return this.bargainId;
	}

	public void setBargainId(int bargainId) {
		this.bargainId = bargainId;
	}

	@Column(name = "BARGAIN_NAME", nullable = false, length = 220)
	public String getBargainName() {
		return bargainName;
	}

	public void setBargainName(String bargainName) {
		this.bargainName = bargainName;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CONTRACT_ID")
	public Contract getContract() {
		return this.contract;
	}

	public void setContract(Contract contract) {
		this.contract = contract;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ID", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PUSER_ID", nullable = false)
	public PUser getPuser() {
		return this.puser;
	}

	public void setPuser(PUser puser) {
		this.puser = puser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROOT_BARGAIN_ID", nullable = false)
	public Bargain getBargain() {
		return this.bargain;
	}

	public void setBargain(Bargain bargain) {
		this.bargain = bargain;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATUS_ID")
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Column(name = "BARGAIN_VER", nullable = false)
	public int getBargainVer() {
		return this.bargainVer;
	}

	public void setBargainVer(int bargainVer) {
		this.bargainVer = bargainVer;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BARGAIN_START", nullable = false, length = 10)
	public Date getBargainStart() {
		return this.bargainStart;
	}

	public void setBargainStart(Date bargainStart) {
		this.bargainStart = bargainStart;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BARGAIN_FINISH", nullable = false, length = 10)
	public Date getBargainFinish() {
		return this.bargainFinish;
	}

	public void setBargainFinish(Date bargainFinish) {
		this.bargainFinish = bargainFinish;
	}

	@Column(name = "BARGAIN_REVENUE")
	public Integer getBargainRevenue() {
		return this.bargainRevenue;
	}

	public void setBargainRevenue(Integer bargainRevenue) {
		this.bargainRevenue = bargainRevenue;
	}

	@Column(name = "BARGAIN_PREPAYMENT")
	public Integer getBargainPrepayment() {
		return this.bargainPrepayment;
	}

	public void setBargainPrepayment(Integer bargainPrepayment) {
		this.bargainPrepayment = bargainPrepayment;
	}

	@Column(name = "BARGAIN_COSTS")
	public Integer getBargainCosts() {
		return this.bargainCosts;
	}

	public void setBargainCosts(Integer bargainCosts) {
		this.bargainCosts = bargainCosts;
	}

	@Column(name = "BARGAIN_PAYMENT_COSTS")
	public Integer getBargainPaymentCosts() {
		return this.bargainPaymentCosts;
	}

	public void setBargainPaymentCosts(Integer bargainPaymentCosts) {
		this.bargainPaymentCosts = bargainPaymentCosts;
	}

	@Column(name = "BARGAIN_FINE")
	public Integer getBargainFine() {
		return this.bargainFine;
	}

	public void setBargainFine(Integer bargainFine) {
		this.bargainFine = bargainFine;
	}

	@Column(name = "BARGAIN_TAX")
	public Integer getBargainTax() {
		return this.bargainTax;
	}

	public void setBargainTax(Integer bargainTax) {
		this.bargainTax = bargainTax;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "bargain")
	public Calendar getCalendar() {
		return this.calendar;
	}

	public void setCalendar(Calendar calendar) {
		this.calendar = calendar;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bargain")
	public Set<Bargaincosts> getBargaincostses() {
		return this.bargaincostses;
	}

	public void setBargaincostses(Set<Bargaincosts> bargaincostses) {
		this.bargaincostses = bargaincostses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bargain")
	public Set<Bargain> getBargains() {
		return this.bargains;
	}

	public void setBargains(Set<Bargain> bargains) {
		this.bargains = bargains;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bargain")
	public Set<Agreed> getAgreeds() {
		return this.agreeds;
	}

	public void setAgreeds(Set<Agreed> agreeds) {
		this.agreeds = agreeds;
	}

}
