package com.cantor.ipplan.db.ud;

// Generated 12.04.2013 19:58:46 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import com.cantor.ipplan.core.DataBridge;
import com.cantor.ipplan.shared.CalendarWrapper;

/**
 * Calendar generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "CALENDAR")
public class Calendar implements java.io.Serializable,DataBridge<CalendarWrapper> {

	private Bargain bargain;
	private String calendarGoogleId;

	public Calendar() {
	}

	public Calendar(Bargain bargain) {
		this.bargain = bargain;
	}

	public Calendar(Bargain bargain, String calendarGoogleId) {
		this.bargain = bargain;
		this.calendarGoogleId = calendarGoogleId;
	}

	@Id
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BARGAIN_ID", unique = true, nullable = false)
	public Bargain getBargain() {
		return this.bargain;
	}

	public void setBargain(Bargain bargain) {
		this.bargain = bargain;
	}

	@Column(name = "CALENDAR_GOOGLE_ID", length = 256)
	public String getCalendarGoogleId() {
		return this.calendarGoogleId;
	}

	public void setCalendarGoogleId(String calendarGoogleId) {
		this.calendarGoogleId = calendarGoogleId;
	}

	@Override
	public CalendarWrapper toClient() {
		CalendarWrapper wrap = new CalendarWrapper();
		wrap.calendarGoogleId = calendarGoogleId;
		return wrap;
	}

	@Override
	public void fromClient(CalendarWrapper data) {
		calendarGoogleId = data.calendarGoogleId;
	}

	@Override
	public void fetch(boolean deep) {
	}

}
