package com.cantor.ipplan.db.ud;

// Generated 12.04.2013 19:58:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.cantor.ipplan.db.up.PUser;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "STATUS")
public class Status implements java.io.Serializable {

	private int statusId;
	private PUser puser;
	private String statusName;
	private Set<Bargain> bargains = new HashSet<Bargain>(0);

	public Status() {
	}

	public Status(int statusId, PUser puser, String statusName) {
		this.statusId = statusId;
		this.puser = puser;
		this.statusName = statusName;
	}

	public Status(int statusId, PUser puser, String statusName,
			Set<Bargain> bargains) {
		this.statusId = statusId;
		this.puser = puser;
		this.statusName = statusName;
		this.bargains = bargains;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "NEWRECORDID")
	@Column(name = "STATUS_ID", unique = true, nullable = false)
	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PUSER_ID", nullable = false)
	public PUser getPuser() {
		return this.puser;
	}

	public void setPuser(PUser puser) {
		this.puser = puser;
	}

	@Column(name = "STATUS_NAME", nullable = false, length = 60)
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Bargain> getBargains() {
		return this.bargains;
	}

	public void setBargains(Set<Bargain> bargains) {
		this.bargains = bargains;
	}

}
